### PR TITLE
fix csv unicode symbol encoding

### LINKED ISSUE #74: Arrow issue in output csv file
The arrow symbol does not show correctly in the output csv file when opened with Excel. 
e.g.
'Prednisone ‚Äì treats ‚Äì chronic obstructive pulmonary disease ‚Äì associates ‚Äì ADAM33 ‚Äì associates ‚Äì asthma'

### PR DESCRIPTION
**Pull request by vincerubinetti**
closes #74 and #75

According to @yhao-compbio, this PR fixes the issue on Microsoft Excel latest (2016?) but not on 2011, running on Mac. In my own testing, this seems to fix the issue for Libre Office Sheets on Ubuntu 18. I can wait to test this on my own Windows 10 machine at home, running the latest MS Office, if desired.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@dongbohu See these two SO posts regarding the weird string prepend:

https://stackoverflow.com/questions/18925210/download-blob-content-using-specified-charset/18925211
https://stackoverflow.com/questions/17879198/adding-utf-8-bom-to-string-blob

File: src/util.js [hunk 1]
```diff
@@ -92,7 +92,9 @@ export function toGradient(number) {
 // data in format [ [A1, B1] , [A2, B2] ]
 export function downloadCsv(data, filename) {
   const fileContent = data.map((cell) => cell.join(',')).join('\n');
-  const blob = new Blob([fileContent], { type: 'text/csv' });
+  const blob = new Blob(['\ufeff', fileContent], {
+    type: 'text/csv;charset=utf-16'
```
Comment (dhimmel) [inline src/util.js]: Curious why uft-16 rather than utf-8? We usually use utf-8, which is more backwards compatable and should be most concise when the majority of characters are ascii https://stackoverflow.com/a/496361/4651668

**Comment by vincerubinetti** [comment]
Added a commit to fix #75 as well.

File: src/util.js (hunk 1 above)
Comment (vincerubinetti) [reply src/util.js]: I forgot that utf8 was also variable length encoding. Thought I needed 16 for the special unicode arrow symbol. Will change to utf-8, though to be honest I'm not sure that that `charset` code does anything at all. Supposedly (according to the SO links above), it's the `\ufeff` that does the trick.
